- examples/flask_demo.py
- examples/starlette_demo.py
- spectree/plugins/flask_plugin.py
`make_response(body, status_code, headers)`
Just let flask functions handle what they support.
> change flask response to jsonify, fix make_response part

- .github/workflows/pythonpackage.yml
- spectree/plugins/falcon_plugin.py
- spectree/plugins/starlette_plugin.py
- spectree/response.py
- spectree/spec.py
- spectree/utils.py
- tests/common.py
- tests/test_config.py
- tests/test_plugin.py
- tests/test_plugin_falcon.py
- tests/test_plugin_flask.py
- tests/test_plugin_starlette.py
- tests/test_response.py
- tests/test_spec.py
- tests/test_utils.py
> Dev: add tests [WIP]

- README.md
- docs/source/config.rst
- docs/source/index.rst
- docs/source/response.rst
- docs/source/utils.rst
- setup.py
> upgrade to v0.2.1

- spectree/plugins/starlette_plugin.py
- tests/test_plugin_starlette.py
This PR fixes an issue where Starlette mounts weren't handled properly. I'm not sure if they were supported to begin with, but at least it doesn't crash on them now (and everything works the same as before).
> Fix issue with Starlette mount

- Makefile
- examples/flask_demo.py
- spectree/config.py
- spectree/spec.py
- spectree/utils.py
- tests/test_utils.py
> Dev: fix headers and cookies generated format in openapi.json

- examples/falcon_demo.py
- setup.py
- spectree/plugins/starlette_plugin.py
> Dev: fix starlette path variables bug in swagger

- spectree/plugins/flask_plugin.py
- tests/test_plugin_flask_blueprint.py
Transparently use blueprint in place of flask app.
> Add flask Blueprint support

- setup.py
- spectree/utils.py
- tests/common.py
- tests/test_utils.py
> fix parameter description bug

- spectree/default_models.py
- spectree/response.py
- spectree/spec.py
- spectree/utils.py
- tests/test_response.py
- tests/test_utils.py
* Add default pydantic model for 422 error
* Remove current 422 error description
> Add 422 default model

- setup.py
- spectree/plugins/flask_plugin.py
- tests/test_plugin_flask.py
> supprt flask x-www-form-urlencoded

- examples/flask_demo.py
- setup.cfg
- setup.py
- spectree/plugins/page.py
- spectree/spec.py
- tests/test_plugin.py
- tests/test_utils.py
> fix nested schema definition

- spectree/plugins/flask_plugin.py
> fix flask any converter produced spec

- spectree/plugins/flask_plugin.py
- spectree/spec.py
- tests/test_plugin.py
* #132 fix nested model
* #110 deep copy model schema
* fix flask endpoint
> fix nested model definition path and schema deepcopy

- spectree/plugins/falcon_plugin.py
Issue https://github.com/0b01001001/spectree/pull/137
> Fix Falcon3 compatibility issue on GET endpoints

- spectree/spec.py
Fixes following error:
```
Structural error at components.securitySchemes
should be object
```
> Fix securityschemes

- spectree/spec.py
> fix security display in redoc page

- spectree/spec.py
- spectree/utils.py
- tests/test_plugin.py
> fix security AND/OR

- spectree/spec.py
- spectree/utils.py
- tests/common.py
- tests/test_plugin.py
- tests/test_plugin_flask.py
> fix issue 166

- examples/security_demo.py
- setup.py
support mark endpoint as deprecated
> Release 0.6.3

- examples/falcon_demo.py
- spectree/config.py
- spectree/plugins/starlette_plugin.py
**Refs**
* https://blog.pilosus.org/posts/2020/01/24/python-f-strings-in-logging/
> Log format

- .github/workflows/pythonpackage.yml
> upgrade actions

- examples/falcon_demo.py
- requirements.txt
- setup.py
- spectree/config.py
- spectree/plugins/base.py
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/starlette_plugin.py
- spectree/spec.py
- tests/test_config.py
- tests/test_spec.py
> Add openapi info

- .pre-commit-config.yaml
- examples/security_demo.py
- setup.py
- spectree/config.py
- spectree/page.py
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/starlette_plugin.py
> Fix swagger oauth2 redirect

- .github/workflows/python-publish.yml
- MANIFEST.in
- Makefile
change to https://github.com/pypa/build
> Refact build

- setup.py
- spectree/plugins/starlette_plugin.py
- tests/test_plugin_starlette.py
> fix req + args parse in starlette

- spectree/utils.py
- tests/common.py
- tests/test_plugin.py
- tests/test_response.py
- tests/test_utils.py
> misc: use hash suffix instead of prefix in get_model_key

- spectree/plugins/falcon_plugin.py
> fix falcon plugin

- Makefile
- setup.py
- spectree/plugins/base.py
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/starlette_plugin.py
- spectree/response.py
- spectree/spec.py
- spectree/utils.py
- tests/test_plugin_falcon_asgi.py
- tests/test_response.py
> support list resp with List[Model]

- spectree/page.py
Seems like there's no breaking change. I did some minor testing, and didnt notice any issue.
> misc: upgrade Swagger UI to v4

- setup.py
> prerelease of 1.0.0a0

- tests/test_response.py
> fix rest annotations in test

- setup.py
- spectree/utils.py
- tests/test_plugin_falcon.py
- tests/test_plugin_falcon_asgi.py
- tests/test_plugin_flask.py
- tests/test_plugin_flask_blueprint.py
- tests/test_plugin_flask_view.py
- tests/test_plugin_starlette.py
> fix: __root__ properties

- mypy.ini
- setup.cfg
> chore: move mypy config to setup.cfg

- spectree/spec.py
- tests/test_plugin.py
Fixes #263
Signed-off-by: Harish Karumuthil <harish2704@gmail.com>
> Fix: Replace slash from generated operationId

- .github/workflows/python-publish.yml
- .github/workflows/pythondoc.yml
- .github/workflows/pythonpackage.yml
- setup.py
> chore: update ci

- README.md
- examples/falcon_asgi_demo.py
- examples/falcon_demo.py
- examples/flask_demo.py
- examples/quart_demo.py
- examples/security_demo.py
- examples/starlette_demo.py
- setup.py
> chore: add quart demo to readme

- spectree/spec.py
- tests/test_spec.py
@kemingy re: https://github.com/0b01001001/spectree/issues/259
> initial version (#259)

- .github/workflows/pythonpackage.yml
- tests/test_plugin_starlette.py
> test: fix starlette cookie in test client

- pyproject.toml
> chore: release 1.0.3

- tests/test_spec.py
> test: fix flask test context

- build.envd
- pyproject.toml
- setup.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/quart_plugin.py
- spectree/plugins/starlette_plugin.py
- tests/test_plugin_falcon.py
> add envd dev env, upgrade black

- .github/CONTRIBUTING.md
- pyproject.toml
* Install "dev" extras, needed for running lint/format checks.
* Fixed reference to non-existent "style" make target, replaced with "style".
* Added pre-commit to "dev" extra requirements.
> Updated contributing docs and added pre-commit requirement.

- pyproject.toml
- spectree/plugins/flask_plugin.py
- tests/flask_imports/dry_plugin_flask.py
> fix: flask mimetype check

- examples/query_list.py
- examples/resp.py
- pyproject.toml
- spectree/plugins/flask_plugin.py
- spectree/utils.py
- tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json
- tests/common.py
- tests/flask_imports/dry_plugin_flask.py
- tests/test_plugin_flask.py
- tests/test_plugin_flask_blueprint.py
- tests/test_plugin_flask_view.py
- fix https://github.com/0b01001001/spectree/issues/355
> fix: flask query list items

- pyproject.toml
- fix https://github.com/0b01001001/spectree/issues/379
> chore: fix the quart dependency in pyproject toml file

- README.md
- pyproject.toml
- spectree/__init__.py
- spectree/_pydantic.py
- spectree/plugins/__init__.py
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/quart_plugin.py
- spectree/plugins/starlette_plugin.py
- spectree/spec.py
- spectree/utils.py
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json
- tests/common.py
- tests/flask_imports/__init__.py
- tests/quart_imports/__init__.py
- tests/test_plugin_falcon.py
- tests/test_plugin_flask.py
- tests/test_plugin_flask_blueprint.py
- tests/test_plugin_flask_view.py
- tests/test_plugin_quart.py
- tests/test_plugin_starlette.py
> feat: skip validation for request & response

- spectree/plugins/flask_plugin.py
it seems we calculated the annotations anyway, even when there was a validation error - its fixed
and decided to use caching to obtain type hints to improve performance
> perf (flask): get annotations when no validation error and use cache for type hints

- pyproject.toml
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/quart_plugin.py
- spectree/plugins/starlette_plugin.py
- spectree/utils.py
- uv.lock
Apple #412 to other frameworks
> perf: cache type hints for other web frameworks

- pyproject.toml
- spectree/plugins/flask_plugin.py
- spectree/utils.py
- tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json
- tests/flask_imports/dry_plugin_flask.py
- tests/test_plugin_flask.py
- tests/test_plugin_flask_blueprint.py
- tests/test_plugin_flask_view.py
- uv.lock
- fix https://github.com/0b01001001/spectree/issues/415
> fix: allow repeated header keys for flask response

- examples/falcon_asgi_demo.py
- examples/falcon_demo.py
- examples/flask_demo.py
- examples/starlette_demo.py
- pyproject.toml
- spectree/models.py
- spectree/plugins/falcon_plugin.py
- spectree/plugins/flask_plugin.py
- spectree/plugins/quart_plugin.py
- spectree/plugins/starlette_plugin.py
- tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json
- tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json
- tests/common.py
- tests/flask_imports/dry_plugin_flask.py
- tests/test_plugin_falcon.py
- tests/test_plugin_falcon_asgi.py
- tests/test_plugin_flask.py
- tests/test_plugin_flask_blueprint.py
- tests/test_plugin_flask_view.py
- tests/test_plugin_starlette.py
- uv.lock
> fix: annotate with the dedicated file type for differente web frameworks

- pyproject.toml
- spectree/plugins/falcon_plugin.py
- uv.lock
- fix https://github.com/0b01001001/spectree/issues/430#issuecomment-3213660670
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Type#directives
> fix: falcon form with `application/x-www-form-urlencoded`

- examples/flask_demo.py
- examples/quart_demo.py
- pylock.legacy.toml
- pylock.toml
- pyproject.toml
- spectree/plugins/flask_plugin.py
- spectree/plugins/quart_plugin.py
- spectree/plugins/werkzeug_utils.py
- tests/conftest.py
- tests/quart_imports/dry_plugin_quart.py
- tests/test_plugin_quart.py
- uv.lock
> fix: quart async test
