spectree/spec.py, tests/test_spec.py
Paths with the same name (but different HTTP method) were being overwritten when rendering the spec.
- Adds bugfix and test case
=> Do not overwrite paths with same name

spectree/spec.py, spectree/utils.py, tests/test_utils.py
This PR removes the `requestBody` field from the generated spec for operations that do not define a `json` validation. This matches the behavior from `flaskerk`.
Before:
```json
{
"paths": {
"/api/v1/users": {
"get": {
"description": "",
"operationID": "list_users__get",
"parameters": [],
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": ""
}
}
}
}
}
}
}
}
```
After:
```json
{
"paths": {
"/api/v1/users": {
"get": {
"description": "",
"operationID": "list_users__get",
"parameters": []
}
}
}
}
```
The empty `requestBody` ref was causing the "Try it out" button in swagger-ui to create invalid  HTTP requests (i.e. GET requests with a JSON request body). Here's the curl representation of what it generated:
```bash
curl -X GET "http://localhost:8080/api/v1/users" -H …
```
=> Remove requestBody field for operations that don't have them

spectree/plugins/flask_plugin.py, spectree/spec.py
This PR includes fixes for following items:
* operationID -> operationId per openapi standard
* operationId value to be more unique (encountered clashes)
* fix for get_json() crash if application/json is set without json body
* also added `after` hook before calling `abort()` on validation error - we return standard json object on any error and needed to modify the default 422 error response in this lib.
=> Fixes for operationId, flask/get_json() and more unique path name

setup.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, tests/common.py, tests/test_plugin_falcon.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_starlette.py
=> fix __root__ 

spectree/plugins/page.py
Text   `# noqa: E501` was showing up in rendered html for _redoc_ documentation.
=> redoc ui fix

spectree/plugins/flask_plugin.py, tests/test_plugin.py, tests/test_plugin_flask.py, tests/test_spec.py
- For accessing app use current_app
- ~~For running test use app_context~~
- Enable tests to run outside `app_context` by allowing `api.spec` to be cached for flask app
Earlier spectree was attaching flask app instance to FlaskPlugin itself. While there is still the case of app attaching to spectree instance, but that would need a broader introspection as it's common api/code for flask, starlette and falcon. Flask uses threadlocal and proxy to request and app instance. I'm not very familiar with starlette and falcon so I'll not disturb them.
=> for flask use current_app (recommended way)

README.md, spectree/config.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/spec.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_flask.py, tests/test_plugin_starlette.py
The current implementation of spectree uses arguments to validate method for declaration of types for query params, request body, cookies and headers and in turn adds a context attribute to request object for all three framework implementations like following:
```python
@app.route("/api/user/<name>", methods=["POST"])
@api.validate(
query=Query,
json=JSON,
cookies=Cookies,
resp=Response(HTTP_200=Resp, HTTP_401=None),
tags=["api", "test"],
after=api_after_handler,
)
def user_score(name):
score = [randint(0, request.context.json.limit) for _ in range(5)]
score.sort(reverse=request.context.query.order)
assert request.context.cookies.pub == "abcdefg"
assert request.cookies["pub"] == "abcdefg"
return jsonify(name=request.context.json.name, score=score)
```
While this is good, but static …
=> enable view function annotation based type detection

README.md
An additional instruction about falcon response. 
Falcon response has both media and body(text in falcon 3.0). Spectree is only validating the media as it's meaningless to validate against string. Therefore I updated the Readme with the additional instruction to make this part more clear to users. And also fix a typo in Readme. :)
=> Update readme with additional instruction about falcon respnse validation

.gitignore, spectree/utils.py, tests/common.py, tests/test_utils.py
=> Catch route parameter keywords from schema when parsing params

spectree/response.py, spectree/spec.py, tests/test_plugin.py, tests/test_response.py, tests/test_utils.py
[BUG] The form with the same name will be overwritten #129
=> Fix form model overwritten

spectree/spec.py
* If multiple OAS files are created, paths defined in other scope are empty in current OAS file. If it is an endpoint with path parameter, Semantic error occurs.
* Example: 
```
Semantic error at paths ./v1/foo/bar/{foo_bar_id}
Declared path parameter foo_bar_id needs to be defined as a path parameter at either the path or operation level
```
=> FIX: empty path enpoints leads to Semantic error => clean empty paths

spectree/response.py, spectree/spec.py, spectree/utils.py, tests/test_plugin.py, tests/test_response.py, tests/test_utils.py
(short hashes are used as they are used in GIT commits)
=> FIX: Code structure (paths) leaking => short hash used instead

spectree/config.py, spectree/spec.py, tests/test_plugin.py, tests/test_plugin_flask.py
Possibility to define security at global (root) level or local (operational) level. It is also possible to override global (root) level by local (operational) level.
> [..] After you have defined the security schemes in the securitySchemes section, you can apply them to the whole API or individual operations by adding the security section on the root level or operation level, respectively. When used on the root level, security applies the specified security schemes globally to all API operations, unless overridden on the operation level. [..]
[Step 2. from [https://swagger.io/docs/specification/authentication/](https://swagger.io/docs/specification/authentication/)]
=> Global security and some changes in security

spectree/config.py, spectree/models.py, spectree/spec.py, tests/test_config.py, tests/test_spec.py
Allows to define servers with url, description and variables as is defined here: https://swagger.io/docs/specification/api-host-and-base-path/
=> Servers definition

spectree/spec.py, tests/test_spec.py
If some item of server is not filled, structural error in OAS occured -> only filled items are generated to OAS specification.
=> Fixed structural error in OAS

spectree/models.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/response.py, spectree/spec.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py, tests/test_response.py, tests/test_spec.py, tests/test_utils.py
I think that the hard coded HTTP status code of `422`, that is used for responses in the event of a validation error, makes sense. However there are quite a lot of projects out there that would prefer to use the status of `400`. In some extreme cases `200` is used for most of the responses, and the actual outcome of the request is described in the response payload. (It isn't RESTful at all, but some projects prefer this for some reason.)
The changes in the PR enable the specification of a custom response status code for validation errors, using the `validation_error_status` parameter. It can be configured globally, for all endpoints, but it can be overridden selectively, for specific endpoints too.
=> Add option for custom validation error status

spectree/config.py, spectree/page.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, tests/test_config.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py
This PR adds a `PAGE_TEMPLATE` configuration option, that allows the users of the library to specify custom documentation page templates. If nothing is specified, the default `swagger` and `redoc` templates are used.
The ability to use custom page templates comes in handy if there is a need to customize Swagger UI for example.
I'm aware of the fact that #75 already exists, and it probably tries to achieve the same goal as this PR. But, the big difference between the two solutions is that the changes in this PR, allow the usage of multiple documentation pages, while the solution in #75 only allows a single documentation page when a custom value is specified. Additionally, in #75 the changes are only implemented for the Falcon plugin.
=> Add option for using custom page templates

spectree/plugins/base.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/spec.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py
This PR adds a new `path_parameter_descriptions` parameter to `SpecTree.validate`. This parameter can be used to provide a description of the endpoint's path parameters. The key is interpreted as the name of the path variable, while the value is used as the description.
Example endpoint:
```python
@app.route('/foo/<foo>/bar/<bar>', methods=['GET'])
@api.validate(path_parameter_descriptions={"foo": "Foo's description."})
def foo(foo, bar):
pass
```
The generated spec:
```json
"/foo/{foo}/bar/{bar}": {
"get": {
"summary": "foo <GET>",
"operationId": "get_/foo/{foo}/bar/{bar}",
"description": "",
"tags": [
],
"parameters": [
{
"name": "foo",
"in": "path",
"required": true,
"schema": {
"type": "string"
},
"description": "Foo's description."
},
{
"name": "bar",
"in": "path",
"required": true, …
```
=> Add option to describe path parameters

spectree/response.py, spectree/utils.py, tests/test_response.py
Hello folks!
The default descriptions provided by the library for the HTTP response status codes are usually good enough to understand the reason for a given response. However, there are some status codes whose meaning might not be so clear. A good example for this might be `409`, which indicates that the request could not be processed because of conflict in the current state of the resource. However, the possible reasons for a conflict might be different for different endpoints. For this reason, it would be very useful to have the option to specify custom descriptions for response status codes.
This PR adds the option to specify response models on endpoints together with a custom description.
```python
@app.route('/foo', methods=['GET'])
@api.validate(
resp=Response(
HTTP_200=Message, …
```
=> Add option to specify custom descriptions for response status codes.

spectree/plugins/flask_plugin.py
This PR fixes a small bug when finding blueprint routes. It's basically not finding any route if you use prefix.
```
from flask import Flask, jsonify, Blueprint
from spectree import Response, SpecTree
app = Flask(__name__)
blueprint_app = Blueprint("my_blueprint_app", __name__, url_prefix="/v1")
api = SpecTree("flask")
@blueprint_app.route("/my-blueprint-endpoint", methods=["GET"])
@api.validate(resp=Response("HTTP_200"), tags=["My Blueprint Endpoints"]
)
def my_blueprint_endpoint():
return jsonify({}), 200
@app.route("/my-app-endpoint", methods=["GET"])
@api.validate(resp=Response("HTTP_200"), tags=["My App Endpoints"]
)
def my_app_endpoint():
return jsonify({}), 200
api.register(blueprint_app)
app.register_blueprint(blueprint_app)
```
I believe this was just a missing `not` in the …
=> Fix blueprint find_routes method

spectree/utils.py, tests/test_utils.py
=> Restored docstring paragraph formatting

spectree/response.py
After a nice PR #182 I began using that feature, but found myself in a position where I had to use the `Response.add_model()` method, which did not support adding descriptions through the tuple-notation or otherwise. I have added this functionality in this PR.
It would have been nice if the `replace` argument were defined as keyword-only (`*, replace: bool = True`) because to me, the logical place to add the description is as a positional argument directly after `model`. Unfortunately, at this time that will break existing code using the `replace` argument as a positional one, since Python will happily accept False as "description", then ignore that as code description and replace the existing model despite the developer intending to not do so.
I would have liked to explicitly check `if …
=> Add description argument to Response.add_model()

Makefile, README.md, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/response.py, spectree/spec.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py
For #160 
This PR adds two new pieces of functionality
- `api.validate` now accepts a `skip_validation` argument that will skip the validation entirely and allow returning invalid responses
- If the view returns a `BaseModel` instance then spectree will automatically call `.dict()` on it and assume it's already validated and skip validation 
I've also added some `pip install`s to the Makefile.
The only issue with this is that Starlette only supports returning hashable types  - which pydantic models are not.
The tests currently fail on this.
Do you have a preference of how to handle this?
I was thinking either 
- Remove support for returning models directly as users can write a wrapper validator to call `.dict()` and set `skip_validation=True`
- Just don't support returning models for …
=> Support skipping validation and returning models

spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py
hi,
there seems to be a regression introduced in #212
it can happen in two situations, each ending with different error:
-  the value of specific status code for `resp` in `@api.validate` is `None`:
```
>       if isinstance(model, resp.find_model(status)):
E       TypeError: isinstance() arg 2 must be a type or tuple of types
```
- `resp` in `@api.validate()` is not declared at all:
```
>       isinstance(model, resp.find_model(status)):
E       AttributeError: 'NoneType' object has no attribute 'find_model'
```
the error was raised in plugins for `flask` and `falcon`, `starlette` was working fine.
this PR adds fix for the two plugins + tests for all three of them.
=> fix: handle case when no view response is defined

spectree/plugins/flask_plugin.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py
`add_url_rule()` in Flask plugin are defined without trailing slash, so only the paths without it work, ie:
```
$ curl -i http://localhost:5000/apidoc/swagger/ |grep HTTP
HTTP/1.0 404 NOT FOUND
$ curl -i http://localhost:5000/apidoc/swagger |grep HTTP
HTTP/1.0 200 OK
```
Default behaviour in Flask regarding trailing slashes is [documented as follows](https://werkzeug.palletsprojects.com/en/2.1.x/routing/#rule-format):
> Rules that end with a slash are “branches”, others are “leaves”. If `strict_slashes` is enabled (the default), visiting a branch URL without a trailing slash will redirect to the URL with a slash 
adding the trailing slash into the routes definition makes both options work:
```
$ curl -i http://localhost:5000/apidoc/swagger/ |grep HTTP
HTTP/1.0 200 OK
$ curl -i …
```
=> Flask: add trailing slash to apidoc routes

spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, tests/test_plugin_starlette.py
this should fix #226
- falcon plugin not affected, since there seems to be only class-based views with split GET and POST dispatchers
- flask tests not changed, as I hope #227 can be merged eventually
=> fix: dont validate JSON data in request which cant provide it

tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py
Moreless identical tests for Flask plugin are written in three different files now (`test_plugin_flask.py`, `test_plugin_flask_view.py`, `test_plugin_flask_blueprint.py`). This PR put them into single places from where they can be imported into each respective test file.
This revealed that the `no_response` view was not tested properly everywhere (see #226), so until that will be resolved, the parameter `json=Query` for given view is commented out.
=> refactoring: define flask tests in single place and reuse them

spectree/utils.py
this makes the logging in default `after` a bit more verbose, as discussed in #229
=> fix: log the validation error in the default  handler

.github/workflows/pythonpackage.yml, Makefile, README.md, docs/source/index.rst, requirements.txt, setup.py, spectree/config.py, tests/test_config.py
Resolve #235
It can be installed with `pip install spectree[email]`. Otherwise, fall back to using a `str` as the type of the email field in the contact model of the config.
=> Make email-validator an optional dependency

Makefile, examples/falcon_demo.py, examples/starlette_demo.py, mypy.ini, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_spec.py
seems like these mypy errors are the last thing making the pipeline fail in #225. Instead of adding `type: ignore` to all newly added imports there, it would be better to disable these errors in one place. This PR is doing that.
`ignore_missing_imports` description in mypy docs:
https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_missing_imports
- config options are moved into its config file instead of calling them manually
=> fix: use mypy.ignore_missing_imports instead of suppressing them everywhere manually

setup.py
Werkzeug 2.2 has marked `parse_rule` as internal so it cant be imported anymore. This function is used in Flask plugin.
See failing pipeline: https://github.com/0b01001001/spectree/actions/runs/2751022576
See their relevant issue: https://github.com/pallets/werkzeug/issues/2464
Adding bounded werkzeug dependency should fix it for now
=> hotfix: add bound for werkzeug dependency due to breaking change

Makefile, README.md, examples/falcon_demo.py, setup.py, spectree/plugins/falcon_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_spec.py
moreless copy-paste of my comment here: https://github.com/0b01001001/spectree/pull/225#issuecomment-1192452387
Falcon 2 was released 2019 and never got any patch above 2.0.0 (see https://pypi.org/project/falcon/#history ), so it seems unsupported anyway.
The reason why I would propse doing this is that Falcon 2 does not support form data. The pipeline in #225 fails right now because `get_media()` does not exist in Falcon 2, so I tried to use `req.media` instead, and I got the following error (with Falcon 2)
```
AssertionError: {"title": "Unsupported media type", "description": "multipart/form-data is an unsupported media type."}
```
Dropping Falcon 2 would then make implementing the form data support easier.
=> drop support for Falcon 2

setup.py, spectree/plugins/flask_plugin.py, spectree/spec.py, spectree/utils.py
I did dig a bit into new Werkzeug and didnt figure out a way how to replace `parse_rule`, so it seems like the fastest way how to make it work is to keep own copy of `parse_rule`.
plus there's microoptimization in separate commit to do `bypass()` before some route parsing
=> add copy of `werkzeug.parse_rule` which is now marked as internal

examples/common.py, examples/falcon_asgi_demo.py, examples/falcon_demo.py, examples/flask_demo.py, examples/starlette_demo.py, setup.py, spectree/__init__.py, spectree/models.py, spectree/plugins/base.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/spec.py, spectree/utils.py, tests/common.py, tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_starlette.py
taking over where #185 was left. This is still very much WIP
- the previous PR made `form` and `json` exclusive (ie. only one can be defined at the time), which I dont think it should be enforced. Here's a use-case where we have right now: we have `/login/` endpoint, which can be called either from a legacy web which submits `<form>`, and it can be also used on a new frontend, which submits JSON payload. As such, one route can have both `form` and `json`.
- previous PR is adding usage of `cgi`, which is about to be deprecated, so it is again removed here
=> add support for form data request 

spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/spec.py
https://docs.python.org/3/library/typing.html#typing.get_type_hints
This properly resolves forward annotations, and fixes annotations when
code uses `from __future__ import annotations`
=> Use typing.get_type_hints instead of .__annotations__

Makefile, spectree/plugins/__init__.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/starlette_plugin.py, spectree/spec.py, tests/import_module/test_falcon_plugin.py, tests/import_module/test_flask_plugin.py, tests/import_module/test_starlette_plugin.py, tests/test_spec.py
=> feat: import plugin using import_module

setup.py, spectree/plugins/flask_plugin.py
* fix https://github.com/0b01001001/spectree/issues/273
=> fix: only call `after` at the end of the validation

spectree/spec.py, tests/test_spec.py
The [operationId](https://swagger.io/docs/specification/paths-and-operations/) path parameter in OpenAPI is used by the most popular code generators to generate names for functions and methods. In the current, auto-generated OpenAPI spec output the operationId parameter’s value is generated from the path of the endpoint. E.g. get_/resource/{resource_id}, which leads to difficult-to-read names in code.
This change allows setting custom operationId through the `operation_id` parameter to the `validate` decorator.
=> Allow endpoints to override its operationId

.github/workflows/pythonpackage.yml, setup.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json, tests/common.py, tests/conftest.py, tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/quart_imports/dry_plugin_quart.py, tests/test_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_quart.py, tests/test_plugin_starlette.py
- fix for https://github.com/0b01001001/spectree/discussions/292
- adding support for `List[Model]` does not look straightforward, so defining `ListModel` is needed for now 
- also the specs is now compared as a whole snapshot via Syrupy instead of manual subset. I had to touch that test, as the list of endpoints there has changed. This way it feels more convenient than updating it manually every time.
=> add test for top-level json list, use syrupy snapshot

spectree/plugins/falcon_plugin.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py
In the falcon plugin, if we use `.data` or `.text`, then the plugin still tries to parse our response from media. Even though `.media` is not present. This PR changes the approach of parsing, we only try to parse the response model if either `.data` or `.text` is not set and `.media` is.
=> Check presence of media before attempting to parse it

spectree/_types.py, spectree/response.py, spectree/spec.py, spectree/utils.py
Following the discussion in https://github.com/0b01001001/spectree/issues/300 this refactor moves the function `get_model_key()` from `utils.py` to `BasePlugin` as a staticmethod.
This will allow custom plugin implementations to override the way the model key is generated as described by @kemingy [here](https://github.com/0b01001001/spectree/issues/300#issuecomment-1515620897).
The following example describes how to create a custom flask plugin that does not append the module hash to the model name:
```python
class YourFlaskPlugin(FlaskPlugin):
def get_model_key(model: ModelType) -> str:
return f"{model.__name__}"
spec = SpecTree(backend=YourFlaskPlugin)
```
EDIT:
> After lots of attempts to refactor through the `staticmethod` on the Base Plugin and continuously running into cyclical …
=> Refactor the get_model_key util function

spectree/_types.py, spectree/spec.py, spectree/utils.py
In the normal behavior the nested models are suffixed with the parent model name. This merge allows to override that behavior in the `Spectree` class. For example:
```python
spec = SpecTree(
nested_naming_strategy=lambda _, child: child 
)
```
=> Add Support for customizing how nested names are generated

spectree/plugins/base.py, spectree/spec.py
This is a continuation of the abandoned [#297 Allow overriding operation_id for each path on a single view function](https://github.com/0b01001001/spectree/pull/297) pull request.
I am a colleague of the author of that PR, and at our company we need to be able to override the implementation for the `operation_id` fields. Extracting that functionality in a separate method like this will enable us to do it.
I followed [this suggestion](https://github.com/0b01001001/spectree/pull/297#discussion_r1156158690) from @kemingy for this PR.
=> Extract the logic for getting the operation_id to a plugin method

Makefile, pyproject.toml, setup.py, spectree/_pydantic.py, spectree/_types.py, spectree/config.py, spectree/models.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, spectree/response.py, spectree/utils.py, tests/common.py, tests/test_config.py, tests/test_response.py, tests/test_spec.py
This is a less involved update to support pydantic v2. Compared to #324, this keeps the internals the same and uses the `pydantic.v1` backport for imports from v2.
=> Support Pydantic v2 with v1 backport

Makefile, spectree/_types.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, spectree/response.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json, tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/quart_imports/dry_plugin_quart.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_quart.py, tests/test_plugin_starlette.py, tests/test_response.py
Currently, `spectree` only partially supports validation of list responses. For example:
```python
class User(BaseModel):
user_id: str
@app.route()
@api.validate(
resp=Response(HTTP_200=List[User])
)
def get_users():
return [
User(user_id="user1").dict(),  # pre-serialization of individual entries is required, or spectree crashes
User(user_id="user2").dict()
]
```
You'll notice in particular that individual entries **must** currently be serialized before returning or `spectree` crashes. This is inconsistent with the rest of the interface, because it's perfectly okay to return models (without serializing them) - so why not list of models?
The change basically updates individual plugins to serialize individual list entries (when needed) before the final response is created. The change is …
=> Support returning lists of unserialized models

Makefile, spectree/_pydantic.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json, tests/common.py, tests/flask_imports/dry_plugin_flask.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_quart.py, tests/test_plugin_starlette.py, tests/test_pydantic.py
Spectree currently does not correctly support using Pydantic root models as response types. Specifying/returning a root model leads to serialisation issues. Couple of examples:
```python
class ApplicationError(BaseModel):
message: str
class User(BaseModel):
user_id: int
class GetUsersResponse(BaseModel):
__root__: Union[list[User], ApplicationError]
@validate(resp=Response(HTTP_200=GetUsersResponse))
def get_users():
return GetUsersResponse(__root__=[User(user_id: 1), User(user_id: 2)])
return GetUsersResponse(__root__=ApplicationError(message="error"))
return [User(user_id: 1), User(user_id: 2)]]  
return ApplicationError(message="error")  
```
This change adds full support for using root model for responses, and makes it possible to:
- Return root model instances directly, in which case …
=> [Proposal] Support Pydantic root model responses

Makefile, spectree/_types.py, spectree/plugins/base.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json, tests/common.py, tests/flask_imports/dry_plugin_flask.py, tests/quart_imports/dry_plugin_quart.py, tests/test_base_plugin.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py, tests/test_plugin_quart.py, tests/test_plugin_starlette.py
As promised, this is a followup [this PR](https://github.com/0b01001001/spectree/pull/338) which unifies and simplifies response validation across plugins. Response validation has been generalised in a single/simple function used across plugins.
=> Unify response validation

spectree/plugins/flask_plugin.py, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py
Following the release of version 1.2.2, the server response's status code generated through "make_response" is no longer being processed accurately. Instead, it is being overwritten with the status code 200.
=> Fix Flask status code processing after release 1.2.2

Makefile, pyproject.toml, spectree/plugins/base.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, spectree/utils.py, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/flask_imports/__init__.py, tests/flask_imports/dry_plugin_flask.py, tests/test_base_plugin.py, tests/test_plugin_flask.py, tests/test_plugin_flask_blueprint.py, tests/test_plugin_flask_view.py
This PR introduces a new function `flask_response_unpack` to parse the Flask response.
BTW also aligned the response validation error message to `err.errors()`.
=> fix: flask & quart resp validation

pyproject.toml, spectree/models.py
=> chore: use set directly for the secuirity scheme requirements

spectree/plugins/flask_plugin.py
This needs to be passed on to the after handler. 
Closes #374
=> Keep track of resp_validation_error in flask plugin

README.md, examples/falcon_asgi_demo.py, examples/falcon_demo.py, examples/flask_demo.py, examples/quart_demo.py, examples/security_demo.py, examples/starlette_demo.py, pyproject.toml, spectree/_pydantic.py, spectree/config.py, spectree/models.py, spectree/page.py, spectree/plugins/falcon_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, spectree/response.py, spectree/utils.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json
- set `annotations = True` by default
- upgrade swagger to v5 to support openapi v3.1.0
- use `typing.Protocol` to support both pydantic v1 & v2
- close #382
=> feat: support pydantic v1 & v2 through Protocol

pyproject.toml, spectree/config.py, spectree/plugins/falcon_plugin.py, spectree/plugins/flask_plugin.py, spectree/plugins/quart_plugin.py, spectree/plugins/starlette_plugin.py, tests/test_plugin_falcon.py
We have pydantic V2 installed in our environemnt, but have been using `from pydantic.v1 import ...`.  With the new changes to support pydantic V2 we are wanting to upgrade Spectree to latest and begin writing new serializers, however, we are not ready to update all of our current models to  be pydantic v2 BaseModels.
Currently if a `ValidationError` is raised, the falcon plug in does not catch it, since `ValidationError` in the plugin is coming from `pydantic`, not `pydantic.v1`.
Since you are aliasing the `pydantic.v1.ValidationError as InternalValidationError`, catching it as well allows us to continue to support our v1 models while we migrate to v2 models.
Looking at the codebase, this looks like a similar issue in the other plugins.  Let me know if you would like me to submit this …
=> Maintain pydantic.v1 model compatibility while using pydantic v2

spectree/plugins/flask_plugin.py, spectree/utils.py
Fix [issue #396](https://github.com/0b01001001/spectree/issues/396)
1. In Pydantic V2 ValidationError, don't include_context which adds the original exception which might not be serializable
2. Follow the lead of `default_before_handler`, and adapt `default_after_handler` to Pydantic V2 ValidationError
=> Fix Flask crashes after Pydantic V2 validator raises ValueError + compatibility issue in default_after_handler

spectree/_pydantic.py
hi!
having pydantic v2 I wouldn't want to call the `dict` method for at least two reasons:
1. its **deprecated** for v2
2. I could have an overridden implementation of the `dict` method and after moving to v2 it would be logical to **rename** it to `model_dump`. Without this change I'll have to debug the spectree code before I understood that my **method with the new name won't be called**
---
p.s. `noqa: SIM108` it's a matter of taste, I can change it to a ternary operator as the linter suggests, if you want that too
=> fix: conversion to dictionary depending on pydantic version

pyproject.toml, spectree/plugins/falcon_plugin.py, tests/__snapshots__/test_plugin/test_plugin_spec[falcon][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_blueprint][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[flask_view][full_spec].json, tests/__snapshots__/test_plugin/test_plugin_spec[starlette][full_spec].json, tests/common.py, tests/test_plugin_falcon.py, tests/test_plugin_falcon_asgi.py, uv.lock
Address the comments from https://github.com/0b01001001/spectree/pull/434/files#r2293604269
1. remove the try...except, it seems those exceptions are not meant to be caught in this layer
2. replace `data` with `get_data()`
3. test both `application/x-www-form-urlencoded` & `multipart/form-data`
4. wrap the stream (this is a bad idea for large files)
It seems the falcon internal stream only lives in the `request.get_media().__iter__`. After that, it will be empty. But we have to go through the `__iter__` here.
Not sure if there are any better ways.
=> fix: keep the falcon file stream in memory
